# Generated by Django 4.1 on 2022-08-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Miss', 'Miss'), ('Mrs.', 'Mrs'), ('Ms', 'Ms')], default='', max_length=60),
        ),
    ]
